[package]
name = "bevy_modding"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_modding_types = { path = "../bevy_modding_types" }

bevy = { version = "0.13.2", features = ["dynamic_linking"] }
libloading = "0.8.3"
